key: Matricule

strict_columns:
  - Agence
  - Nom
  - Prenom
  - Code postal

fuzzy_columns:
  - Adresse

fuzzy_threshold: 85

aliases:
  Code postal: ["CP", "CodePostal", "Postal Code"]
  Prenom: ["Prénom", "FirstName"]
  Nom: ["LastName"]
  Adresse: ["Adresse complète", "Address"]


